const LABELS_TEXT_ENGLISH = {
  category: 'Category',
  categoryHelpIntro:
    'Categories help you organize your fridge by grouping similar items like Dairy, Vegetables, or Snacks. This makes it easier to find what you need and track freshness.',
  categoryName: 'Category Name',
  categoryNamePlaceholder: 'e.g. Fruits',
  chooseIcon: 'Choose Icon',
  accentColor: 'Accent Color',
  quickSuggestions: 'Quick Suggestions',
  suggestionFruits: 'Fruits',
  suggestionVegetables: 'Vegetables',
  suggestionMeatFish: 'Meat & fish',
  suggestionDairy: 'Dairy',
  suggestionFrozen: 'Frozen',
  saveCategory: 'Save Category',
  preserveTheFreshness: 'Preserve the Freshness',
  itemHelpIntro:
    'Catalog your ingredients with precision to optimize your kitchen inventory and keep track of freshness.',
  itemDatePlaceholder: 'dd/mm/yyyy',
  itemNamePlaceholder: 'e.g. Apples',
  itemQuantityPlaceholder: '0',
  permanentShoppingListHint: 'Add to persistent shopping list when empty',
  saveItem: 'Save Item',
  name: 'Name',
  quantity: 'Quantity',
  dateAdded: 'Date Added',
  expDate: 'Expiration Date',
  shouldAlwaysBePresent: 'Should always be present',
  unit: 'Unit',
  piece: 'Piece',
  gram: 'Gram',
  kilogram: 'Kilogram',
  liter: 'Liter',
  milliliter: 'Milliliter',
  fridgeExpLabelExpires: 'Expires',
  fridgeExpLabelWarning: 'Warning',
  fridgeExpLabelCritical: 'Critical',
  fridgeExpLabelExpired: 'Expired',
  fridgeExpBadgeToday: 'Today',
  fridgeExpBadgeTomorrow: 'Tomorrow',
  fridgeExpBadgeInDays: 'In %{count} days',
};

const LABELS_TEXT_UKRAINIAN = {
  category: 'Категорія',
  categoryHelpIntro:
    'Категорії допомагають упорядкувати холодильник: наприклад, молочні продукти, овочі чи перекуси. Так легше знайти потрібне й стежити за свіжістю.',
  categoryName: 'Назва Категорії',
  categoryNamePlaceholder: 'напр. Фрукти',
  chooseIcon: 'Виберіть Іконку',
  accentColor: 'Колір Акценту',
  quickSuggestions: 'Швидкі Підказки',
  suggestionFruits: 'Фрукти',
  suggestionVegetables: 'Овочі',
  suggestionMeatFish: "М'ясо та риба",
  suggestionDairy: 'Молочне',
  suggestionFrozen: 'Заморозка',
  saveCategory: 'Зберегти Категорію',
  preserveTheFreshness: 'Збережіть Cвіжість',
  itemHelpIntro:
    'Записуйте продукти точно, щоб краще керувати запасами на кухні й стежити за свіжістю.',
  itemDatePlaceholder: 'дд/мм/рррр',
  itemNamePlaceholder: 'напр. Яблука',
  itemQuantityPlaceholder: '0',
  permanentShoppingListHint:
    'Додавати до постійного списку покупок, коли закінчиться',
  saveItem: 'Зберегти Продукт',
  name: 'Назва',
  quantity: 'Кількість',
  dateAdded: 'Дата Додавання',
  expDate: 'Термін Придатності',
  shouldAlwaysBePresent: 'Завжди має бути в наявності',
  unit: 'Одиниця',
  piece: 'Штука',
  gram: 'Грам',
  kilogram: 'Кілограм',
  liter: 'Літр',
  milliliter: 'Мілілітр',
  fridgeExpLabelExpires: 'Термін',
  fridgeExpLabelWarning: 'Увага',
  fridgeExpLabelCritical: 'Критично',
  fridgeExpLabelExpired: 'Прострочено',
  fridgeExpBadgeToday: 'Сьогодні',
  fridgeExpBadgeTomorrow: 'Завтра',
  fridgeExpBadgeInDays: 'Через %{count} дн',
};

export { LABELS_TEXT_ENGLISH, LABELS_TEXT_UKRAINIAN };
