const LABELS_TEXT_ENGLISH = {
  category: 'Category',
  categoryHelpIntro:
    'Categories help you organize your fridge by grouping similar items like Dairy, Vegetables, or Snacks. This makes it easier to find what you need and track freshness.',
  categoryName: 'Category name',
  categoryNamePlaceholder: 'e.g. Fruits',
  chooseIcon: 'Choose icon',
  accentColor: 'Accent color',
  quickSuggestions: 'Quick suggestions',
  suggestionFruits: 'Fruits',
  suggestionVegetables: 'Vegetables',
  suggestionMeatFish: 'Meat & fish',
  suggestionDairy: 'Dairy',
  suggestionFrozen: 'Frozen',
  saveCategory: 'Save category',
  name: 'Name',
  quantity: 'Quantity',
  dateAdded: 'Date added',
  expDate: 'Expiration date',
  shouldAlwaysBePresent: 'Should always be present',
  unit: 'Unit',
  piece: 'Piece',
  gram: 'Gram',
  kilogram: 'Kilogram',
  liter: 'Liter',
  milliliter: 'Milliliter',
};

const LABELS_TEXT_UKRAINIAN = {
  category: 'Категорія',
  categoryHelpIntro:
    'Категорії допомагають упорядкувати холодильник: наприклад, молочні продукти, овочі чи перекуси. Так легше знайти потрібне й стежити за свіжістю.',
  categoryName: 'Назва категорії',
  categoryNamePlaceholder: 'напр. Фрукти',
  chooseIcon: 'Іконка',
  accentColor: 'Колір акценту',
  quickSuggestions: 'Швидкі підказки',
  suggestionFruits: 'Фрукти',
  suggestionVegetables: 'Овочі',
  suggestionMeatFish: "М'ясо та риба",
  suggestionDairy: 'Молочне',
  suggestionFrozen: 'Заморозка',
  saveCategory: 'Зберегти категорію',
  name: 'Назва',
  quantity: 'Кількість',
  dateAdded: 'Дата додавання',
  expDate: 'Термін придатності',
  shouldAlwaysBePresent: 'Завжди має бути в наявності',
  unit: 'Одиниця',
  piece: 'Штука',
  gram: 'Грам',
  kilogram: 'Кілограм',
  liter: 'Літр',
  milliliter: 'Мілілітр',
};

export { LABELS_TEXT_ENGLISH, LABELS_TEXT_UKRAINIAN };
